### PR TITLE
Directed nsi

### PR DESCRIPTION
**Pull request by jdonges**

### CODE REVIEW

**Comment by jdonges** [comment]
@fkuehlein can you deal with these conflicts and merge?

**Comment by fkuehlein** [comment]
Sure, will do!

**Comment by fkuehlein** [comment]
Hold on, there was a problem with my VSCode's merge editor:

It did not show great parts of the changes to `network.py` from 8bca11e and d23d30b, which is why they got lost in 7d703d0. Probably couldn't handle the large diff, could not resolve this problem on a second try. 

I will therefore just manually copy-paste the changes from the original two commits and re-commit them to this branch.

**Comment by fkuehlein** [comment]
two notes on the above:

- In [] i removed `Network.nsi_degree_uncorr()` and `Network.nsi_local_clustering_uncorr()`, which are now covered by  in `nsi_degree()`/`nsi_local_clustering()`, aligning them with other n.s.i. methods such as `nsi_indigree()`. I hope I didn't oversee any further purpose of those removed methods?  

  When trying to add a respective test I noticed a bug in `nsi_local_clustering(typical_weight=x)`. See #206 for details.

- As of 2d9616c, many `nsi_*` methods' cache decorators were commented out, probably as a temporary workaround to #148. However, there are many more potentially affected cases so the issue is not fully worked around.

**Comment by ntfrgl** [comment]
Looks good to me. I've only added some minor commits related to maintenance and CI. The caching issues will be addressed in the dedicated issue mentioned above.

Thank you, @mensch72 and @fkuehlein!

**Comment by fkuehlein** [comment]
Awesome, thanks for the additions and cleanup @ntfrgl!

Just one thing I don't understand: Why did CodeCov even include `tests/test_core/test_network.py` in the [report](https://app.codecov.io/gh/pik-copan/pyunicorn) now?

m.c. everyone :-)

**Comment by ntfrgl** [comment]
You're welcome.

I'm not quite sure what the presumptions of your question are, since you changed that file. Here is some relevant documentation, maybe it can clarify matters:
- https://coverage.readthedocs.io/en/7.3.4/source.html
- https://pytest-cov.readthedocs.io/en/latest/reporting.html
- https://docs.codecov.com/docs/coverage-percentages

**Comment by fkuehlein** [comment]
Right, what I was implying was that CodeCov previously did not measure the test-files themselves at all, because of course we don't want to start testing tests, and therefore me changing `test_network.py` should not make a difference. This is because the source-directory for `pytest-cov` is specified as

https://github.com/pik-copan/pyunicorn/blob/a8d43129cbc8c0898ff714ca62cff709cfabcd25/setup.cfg#L119

Only in that latest coverage report `test_network.py` is now appearing as the only test-file, and if I run pytest on my machine again it does, too. I was just wondering if your changes to the pytest configuration in combination with the multiple configuration files might have corrupted that above setting in some way? Could not find find out how yet ...

**Comment by fkuehlein** [comment]
Also, when running the test suite I now get a dtype-mismatch from [`Network.nsi_betweenness()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/core/network.py#L3336) which probably originates from e3446bb, only I could not resolve it yet.

```
File pyunicorn/src/pyunicorn/core/network.py:3336, in Network.nsi_betweenness(self, parallelize, **kwargs)
   3334         pool.join()
   3335 else:
-> 3336     betw_w = worker(to_cy(targets, NODE))
   3337 return betw_w / w

File src/pyunicorn/core/_ext/numerics.pyx:412, in pyunicorn.core._ext.numerics._nsi_betweenness()

ValueError: Buffer dtype mismatch, expected 'NODE_t' but got 'signed char'"
```

The two arguments expected by `core._ext._nsi_betweenness()` to be of `NODE_t` type are `flat_neighbors` and `targets`, which are both explicitly cast using `to_cy()`, so I don't really understand why this error occurs. Also, it apparently did not occur on the Travis build. Any idea?

**Comment by ntfrgl** [comment]
> I was just wondering if your changes to the pytest configuration in combination with the multiple configuration files might have corrupted that above setting in some way?

Ah, I see the problem now, thanks for pointing it out. Let me know if f374ffd behaves as you'd expect.

**Comment by ntfrgl** [comment]
> Also, when running the test suite I now get a dtype-mismatch from [`Network.nsi_betweenness()`](https://github.com/pik-copan/pyunicorn/blob/master/src/pyunicorn/core/network.py#L3336) which probably originates from [e3446bb](https://github.com/pik-copan/pyunicorn/commit/e3446bb55c30203cb085b428b10088e85a9a5aef), only I could not resolve it yet.

That commit changed the order of arguments in the Cython function signature, in order to be able to parallelise using just a `partial` wrapper, and thus to avoid a serialisation problem with the `multiprocessing` module from the standard library.

> Also, it apparently did not occur on the Travis build. Any idea?

You probably just need to recompile/reinstall locally after that change.

**Comment by fkuehlein** [comment]
> You probably just need to recompile/reinstall locally after that change.

Ah sure, my bad!

> Let me know if https://github.com/pik-copan/pyunicorn/commit/f374ffda77cb2119fa7b95b4e7a6423b32eaad0e behaves as you'd expect.

It does, thanks!

**Pull request merged**
