### PR TITLE
Initial commit to include directed degree measures in the network class

### PR DESCRIPTION
**Pull request by wbarfuss**
New methods =nsi_indegree= and =nsi_outdegree= introduced so far.
_Open Questions / Points to discuss_
- Shall the =typical_weight= fuctionality also be available for directed degrees?
- Shall there be a =link_attribute= keyword for all the degree measues, by that including =strength= measures?
- Does it make any sense to have the =sp_nsi_diag_k= and the =sp_nsi_diag_k_inv= methods written in the code between all the degree measures? If no, shall they be moved to another sensible place?

### CODE REVIEW

**Comment by wbarfuss** [comment]
Hi, two things:
1) Unfortunately it turned out that it is much more suitable to work on the issue regarding Delphines paper in only one branch. So I started by now implementing the clustering motifs here as well, although the branch is called nsi_degree. I don't know if we should or can rename something?
2) pylint discovers two new "error":
C:  1, 0: Too many lines in module (5670/5600) (too-many-lines)
R:122, 0: Too many public methods (113/110) (too-many-public-methods)
How shall we proceed with this?

**Comment by wbarfuss** [comment]
Another point:
local_clustering works with directed and undirected networks by treating the directed as undirected links. nsi_local_clustering works only with undirected networks. Shall this be harmonized?

**Comment by ntfrgl** [comment]
- Everything except the ``t = ...; T = ...`` lines in the motif clustering methods can be refactored into a helper function.
- Warning thresholds can be configured in ``pylintrc`` and are astronomical already.

**Comment by wbarfuss** [comment]
I think, that would solve than issue #49

**Comment by ntfrgl** [comment]
Please use ``tests.test_doctests.r()`` in doctests with floats, see e.g. ``Network.local_clustering()``.

**Comment by wbarfuss** [comment]
I hope I didn't forget any

**Pull request merged**
