### PR TITLE
CI: add build jobs for macOS and Windows in `travis.yml`

### PR DESCRIPTION
**Pull request by fkuehlein**
I will have to do this step-wise to see what works, as Travis CI documentation does not really cover our specific case. Will start with the macOS job, add a Windows job after that, and finally add the Linux jobs back again, hopefully not needing too many builds along the way.

### CODE REVIEW

**Comment by fkuehlein** [comment]
- __macOS__: building successfully, although wasn't yet able to combine with the linux jobs.

- __Windows__: Apparently cannot install miniconda on windows using `miniconda.exe` without having a GUI. 
Tried going with `choco install miniconda3` instead, but cannot find `conda` command afterwards, maybe `/AddToPath` not working?

  Will probably just go with `choco install python` instead.

**Comment by fkuehlein** [comment]
This PR is becoming a bit of a mess, but I've run into multiple issues here. @ntfrgl, sorry for bothering you with it at this stage, but maybe you have a quick idea on what direction to proceed? I feel like I'm acting pretty clumsy on this, have no experience whatsoever with windows and/or git bash, don't want to waste too much time and credits...

### i. combining the linux and macos jobs

macOS builds are running fine, although taking about 20 minutes which could be sped up maybe. Only I could not figure out how to expand the linux build matrix with a single macOS build (see 5145e49 for my most recent try). Therefore, in f66d3e3 I just added all linux jobs explicitly, which is not very elegant but works.

### ii. installing miniconda on windows vm

I tried installing miniconda two ways:

- download the .exe file with `wget` or `curl` and do a silent install (`/S` flag) (see 36c107e and fe538c9) as proposed by [Anaconda docs](https://docs.conda.io/projects/miniconda/en/latest/):

  ```bash
  $> curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o miniconda.exe
  $> start /wait "" miniconda.exe /S
  ```

  Problem is the build will just time out with no response after 10m. I tried the same in cmd.exe on a Windows machine and it finished within a minute. Seems to me that the second command is run before the first one is finished and thus will never succeed (see build logs).

- install via chocolatey: 

  ```bash
  $> choco install miniconda3 --params="'/S /InstallationType=JustMe /AddToPath=1 /D=%UserProfile%\miniconda'"
  ```

  Problem is it won't find the `conda` command after that (see 46615ec), although the `/AddToPath` flag is set. Probably need to refresh environment variables but `refreshenv` command is not found either (see 8db98d0).

now an alternative would be to go without conda and just pip instead, of course...

**Comment by fkuehlein** [comment]
Finally got the `choco install miniconda3` to run in 7698e85 thanks to an example found [here](https://travis-ci.community/t/python-support-on-windows/241/10).

Now `pyunicorn` will install fine, but when trying to run tests I get this error from `matplotlib.font_manager` when importing `igraph`:

```
..\..\..\miniconda\envs\test-env\lib\site-packages\matplotlib\font_manager.py:215: in win32FontDirectory
    return os.path.join(os.environ['WINDIR'], 'Fonts')
..\..\..\miniconda\envs\test-env\lib\os.py:679: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'WINDIR'
```

see [build log](https://app.travis-ci.com/github/pik-copan/pyunicorn/builds/268450609) for full error message. I checked for the `$WINDIR` environment variable in 147a406 and it is correctly set (see [build log](https://app.travis-ci.com/github/pik-copan/pyunicorn/builds/268456838#L1210)), don't understand why matplotlib won't find it and hence giving up for today. Don't think installing `miniconda` via `choco` is optimal anyway because it is limited to `python=3.9` and does not appear to be maintained ...

**Comment by fkuehlein** [comment]
Same problem occurs without conda, just using pip.

**Comment by ntfrgl** [comment]
@fkuehlein, thank you for getting all the tedious work done! This is a big step forward for the project.

In my commits above, I resolved the remaining issues you mentioned, and achieved some simple speedups.

**Comment by fkuehlein** [comment]
Thank you lots, @ntfrgl! Great to see all green checks on this ... with the `travis.yml` containing everything we need yet being boiled down to improved readability and fair speed, I'll merge this right away. :)

**Pull request merged**
